### ISSUE TITLE
Player doesn't shot bullets

### ISSUE THREAD

**Issue by S3T4NT4** [zigurous/unity-space-invaders-tutorial#1]
Hi, i have an issue.
I followed the tutorial and downloaded the project and they work as intended, but if i try to export and import the games to another projects the player stops shoting lasers (sometimes he does but they disapear aferwards). Is it because of the collisions of the player or i changed something in the project?
Thanks

**Comment by adamgraham** [comment]
> Hi, i have an issue. I followed the tutorial and downloaded the project and they work as intended, but if i try to export and import the games to another projects the player stops shoting lasers (sometimes he does but they disapear aferwards). Is it because of the collisions of the player or i changed something in the project? Thanks

If you copy over the files to another project, then some of the references might break. For example, if one of the scripts references a prefab asset, then you might need to reassign that reference. Make sure the prefabs and any other object references are still assigned on all of your components/scripts.
